cigarette:
  duration: 0.1
  threshold: 0.8
closed_eyes:
  duration: 1.0
  threshold: 0.8
closed_eyes_duration:
  tracking_window: 60  # Время отслеживания в секундах (последняя минута)
  threshold: 10        # Пороговое значение в секундах (максимальное время закрытых глаз)
head_pose:
  duration: 1.8
  pitch: 0.5
  yaw: 1.5
no_belt:
  duration: 1.5
  threshold: 0.8
no_driver:
  duration: 0.5
  threshold: 0.8
no_face:
  duration: 0.5
  threshold: 0.8
phone:
  duration: 0.5
  threshold: 0.8
system:
  model: './yolo11'
  rtsp_stream_url: rtsp://192.168.0.173:8554/stream  # URL для получения исходного видеопотока
  shape_predictor: 'shape_predictor_68_face_landmarks.dat'
  alarm_host: '192.168.0.173'  # Хост для отправки тревог
  alarm_port: 8008         # Порт для отправки тревог
  target_host: '192.168.0.173' # Хост для отправки тревог (используется в send_dsm_alarm)
  target_port: 10000       # Порт для отправки тревог (используется в send_dsm_alarm)
  output_stream_url: 'rtsp://localhost:8554/processed'  # URL для публикации обработанного видеопотока
yawn:
  duration: 0.5
  threshold: 0.3
rockchip:
  ip: '192.168.0.173'  # IP адрес рокчипа
  user: 'orangepi'      # Пользователь для SSH подключения
  password: 'orangepi'  # Пароль для SSH подключения
  config_path: '/home/orangepi/opi5test/core/config.yaml'  # Путь к конфигу на рокчипе
  api_port: 8000        # Порт API сервиса на рокчипе
