cigarette:
  duration: 0.1
  threshold: 0.8
closed_eyes:
  duration: 1.0
  threshold: 0.8
closed_eyes_duration:
  tracking_window: 60  # Время отслеживания в секундах (последняя минута)
  threshold: 10        # Пороговое значение в секундах (максимальное время закрытых глаз)
head_pose:
  duration: 1.8
  pitch: 0.5
  yaw: 1.5
no_belt:
  duration: 1.5
  threshold: 0.8
no_driver:
  duration: 0.5
  threshold: 0.8
no_face:
  duration: 0.5
  threshold: 0.8
phone:
  duration: 0.5
  threshold: 0.8
system:
  rtsp_stream_url: rtsp://192.168.0.173:8554/stream  # URL для получения исходного видеопотока
  alarm_host: '192.168.0.173'  # Хост для отправки тревог
  alarm_port: 8008         # Порт для отправки тревог
yawn:
  duration: 0.5
  threshold: 0.3
