version: '3.8'

services:
  web_interface:
    build: .
    container_name: web_interface
    ports:
      - "7860:7860"
    environment:
      - ALARM_WS_URL=ws://192.168.0.172:8008
    volumes:
      - ./web_config.json:/app/web_config.json
    restart: unless-stopped
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
